- - - # settings for alternative exhibition
- settings:
  default_lang        : en
  base_url            : https://linkedart.example.com/
  directory           : alternative_exhibition/
  a_collection        : data/a_collection
  b_mapped            : data/b_mapped
  c_linked_art        : data/c_linked_art
  template            : template.jsonnet
...